Repository FRONTENDSCHOOL5/final-12-spport, pull requests merged in 2023-08, with the labels that each got.

#114 [Design] 반응형
  src/components/List/CardGrid.jsx
  src/components/Profile/ProfleStyle.jsx
  src/pages/EditProfile.jsx
  src/pages/Signup.jsx
Labels: design

#115 [Feat] 구조적 헤딩 추가
  src/components/Follow/Followers.jsx
  src/components/Follow/Followings.jsx
  src/components/List/CardListItem.jsx
  src/components/Post/PostList.jsx
  src/components/Profile/CommonProfile.jsx
  src/components/Profile/MyProfile.jsx
  src/components/Profile/SameTag.jsx
  src/components/Profile/TeamProfile.jsx
  src/components/Profile/UserProfile.jsx
  src/pages/EditProfile.jsx
  src/pages/Home.jsx
  src/pages/Post.jsx
  src/pages/Upload.jsx
Labels: feat

#120 [Design,Feat,Fix] 내브바 추가, 프로필 수정 버그 수정
  src/components/Common/NavBar.jsx
  src/components/Post/BtnGroup.jsx
  src/components/Post/PostList.jsx
  src/components/Profile/CommonProfile.jsx
  src/components/Profile/MyProfile.jsx
  src/components/Profile/TeamProfile.jsx
  src/components/Profile/UserProfile.jsx
  src/pages/EditProfile.jsx
  src/pages/Home.jsx
  src/pages/Profile.jsx
Labels: bug, design, feat, Profile, Home, Post

#121 [Design] 반응형
  src/assets/image/icon-more-white.svg
  src/assets/logo/logo-small.svg
  src/assets/logo/logo-white.svg
  src/components/Comment/InputComment.jsx
  src/components/Common/Filter/FeedFilter.jsx
  src/components/Common/Header/Header.jsx
  src/components/Common/Header/SearchBox.jsx
  src/components/Common/NavBar.jsx
  src/components/List/CardGrid.jsx
  src/components/Profile/ProfleStyle.jsx
  src/components/Profile/TeamProfile.jsx
  src/pages/AddGame.jsx
  src/pages/Error.jsx
  src/pages/Follow.jsx
  src/pages/Home.jsx
  src/pages/PlayerList.jsx
  src/pages/Profile.jsx
  src/pages/Schedule.jsx
Labels: design

#122 [Design, Feat] 반응형
  src/components/Common/Header/Header.jsx
  src/components/Common/Header/SearchBox.jsx
  src/pages/AddGame.jsx
  src/pages/Follow.jsx
  src/pages/Home.jsx
  src/pages/Post.jsx
  src/pages/Schedule.jsx
  src/pages/Search.jsx
Labels: design, feat

#124 [Feat, Fix] 팔로워, 팔로잉 페이지 헤더 변경, meta 태그 및 타이틀 추가, 댓글 입력 버그 수정
  src/App.js
  src/components/Post/Post.jsx
  src/index.js
  src/pages/AddGame.jsx
  src/pages/EditPost.jsx
  src/pages/EditProfile.jsx
  src/pages/Follow.jsx
  src/pages/PlayerList.jsx
  src/pages/Post.jsx
  src/pages/Profile.jsx
  src/pages/Schedule.jsx
  src/pages/Upload.jsx
Labels: feat, fix

#132 [Feat] PlayerList 축구, 배구 선수정보 알 수 있도록 수정
  src/pages/PlayerList.jsx
Labels: feat

#133 [Refactor] 로그인 수정
  src/pages/Login.jsx
Labels: refactor, Login

#136 📝Docs: Update README.md
  README.md
Labels: docs

#137 [Docs] Update README.md
  README.md
Labels: docs
