Repository FRONTENDSCHOOL5/final-12-spport, pull requests merged in 2023-07, with the labels that each got.

#103 Design, Feat
  src/App.js
  src/assets/image/icon-x.svg
  src/components/Comment/InputComment.jsx
  src/components/Common/Header/Header.jsx
  src/components/Common/Header/SearchBox.jsx
  src/components/Common/Input.jsx
  src/components/Common/Modals/BottomSheet.jsx
  src/components/Common/Modals/Modal.jsx
  src/components/Common/NavBar.jsx
  src/components/Post/Post.jsx
  src/components/Post/PostList.jsx
  src/components/Profile/ProfleStyle.jsx
  src/components/Profile/TeamProfile.jsx
  src/pages/AddGame.jsx
  src/pages/EditProfile.jsx
  src/pages/Follow.jsx
  src/pages/PlayerList.jsx
  src/pages/Post.jsx
  src/pages/Schedule.jsx
  src/pages/Signup.jsx
  src/pages/Splash.jsx
  src/pages/Welcome.jsx
  src/style/GlobalStyles.js
Labels: design, feat

#104 Feat, Fix: 같은 태그 검색 기능, 모달/바텀시트 포커스
  src/components/Common/Modals/BottomSheet.jsx
  src/components/Common/Modals/Modal.jsx
  src/components/Profile/CommonProfile.jsx
  src/components/Profile/SameTag.jsx
  src/routes/Router.jsx
Labels: feat, fix, Profile

#105 Refactor, Rename: React query 추가, 데이터 추가
  package-lock.json
  package.json
  src/api/GameAPI/AddGameAPI.js
  src/api/GameAPI/PostGameAPI.js
  src/api/GameAPI/TeamProfileGameAPI.js
  src/api/PostAPI.js/CommentAPI.js
  src/assets/data/baseball_games.json
  src/assets/data/baseball_players.json
  src/assets/data/soccer_games.json
  src/assets/data/soccer_players.json
  src/assets/data/sport_users.json
  src/assets/data/volleyball_games.json
  src/assets/data/volleyball_players.json
  src/components/Comment/InputComment.jsx
  src/components/Comment/ViewComment.jsx
  src/data/sport_bs_users.json
  src/hook/useComment.js
  src/hook/usePost.js
  src/index.js
  src/pages/EditProfile.jsx
  src/pages/Home.jsx
  src/pages/PlayerList.jsx
  src/pages/Post.jsx
  src/pages/Signup.jsx
Labels: docs, feat, refactor, rename
